### ISSUE TITLE
[Installation] Erreur lors du lancement de la commande rake after_party:run

### ISSUE THREAD

**Issue by syji35** [demarches-simplifiees/demarches-simplifiees.fr#9683]
Installation de démarches simplifiées sur une VM debian avec le tag 2023-10-30-01

Lorsque je procède à l'installation, je lance une commande pour init la base deo
```
bundle exec rake db:setup
```

Ensuite je lance la commande 
```
bundle exec rake after_party:run
```

Cette commande échoue sur le script de déployment "process_expired_dossiers_en_construction"

Voici les logs :  
```
demarches_ds.1.b2obpquwrmi6@prod-ds    | Tasks: TOP => db:migrate
demarches_ds.1.b2obpquwrmi6@prod-ds    | (See full trace by running task with --trace)
demarches_ds.1.b2obpquwrmi6@prod-ds    | Created database 'demarches'
demarches_ds.1.b2obpquwrmi6@prod-ds    | Create test user 'test@exemple.fr'
demarches_ds.1.b2obpquwrmi6@prod-ds    | Running deploy task 'cleanup_deleted_dossiers'
demarches_ds.1.b2obpquwrmi6@prod-ds    | Running deploy task 'process_expired_dossiers_en_construction'
demarches_ds.1.b2obpquwrmi6@prod-ds    | rake aborted!
demarches_ds.1.b2obpquwrmi6@prod-ds    | NoMethodError: undefined method `send_expiration_notices' for ExpiredDossiersDeletionService:Class
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/lib/tasks/deployment/20200401123317_process_expired_dossiers_en_construction.rake:10:in `block (2 levels) in <main>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.9.0/lib/sentry/rake.rb:26:in `execute'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (3 levels) in <main>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `each'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (2 levels) in <main>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/sentry-ruby-5.9.0/lib/sentry/rake.rb:26:in `execute'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /usr/local/bin/bundle:25:in `load'
demarches_ds.1.b2obpquwrmi6@prod-ds    | /usr/local/bin/bundle:25:in `<main>'
demarches_ds.1.b2obpquwrmi6@prod-ds    | Tasks: TOP => after_party:process_expired_dossiers_en_construction
demarches_ds.1.b2obpquwrmi6@prod-ds    | (See full trace by running task with --trace)
debian@prod-ds:~$

```

**Comment by tchak** [comment]
Corrigé par c015f5ad74 : after_party a été retiré (gem, initializer, générateur et tâches `lib/tasks/deployment/`), la commande `rake after_party:run` n'existe donc plus. Les migrations de données passent désormais par MaintenanceTasks.

À noter : `doc/UPGRADING.md` mentionne encore l'ancienne commande — documentation à mettre à jour.


Je ferme cette issue ; n’hésitez pas à la rouvrir si le comportement constaté diffère.
